version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: MongoDB.Driver
    versions:
    - 2.11.6
    - 2.12.0
    - 2.12.1
  - dependency-name: MongoDbGenericRepository
    versions:
    - 1.4.5
    - 1.4.6
  - dependency-name: Microsoft.Extensions.Identity.Core
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.TestHost
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: Microsoft.VisualStudio.Web.CodeGeneration.Design
    versions:
    - 5.0.1
  - dependency-name: Microsoft.ApplicationInsights.AspNetCore
    versions:
    - 2.16.0
